#!/bin/bash
# /////////////////// defining parameters for a rectangular wg . geometry in ribbon.bem /////////////////////////////
# //     N   = the total number of parametrization points
# //     w   = total width of wg      || x 
# //     h   = total thickness of wg  || z
#//     L   = lenght of the substrate is 2*L+W  || x
#//     R = radius of the virtual geometry (arc)
# //     ze  = impact parameter is h/2+ze. ze distance between electron and wg surface 

N=${1:-500}
W=${2:-500}
h=${3:-300}
L=${4:-100}
Eelectron_keV=${5:-200}
Energy_eV=${6:-0.1}

NOFraw='EELS_comsol2_N'${N}'_W'${W}'nm_h'${h}'nm_L'${L}'nm_Ee'${Eelectron_keV}'keV_energy'${Energy_eV}
NOF=$(echo $NOFraw | sed -e 's/\.//g')

NOFfiles='_EELS_along_z'

#bem file
mkdir -p bemfiles${NOFfiles}
mkdir -p datfiles${NOFfiles}
mkdir -p shfiles${NOFfiles}

cat > bemfiles${NOFfiles}/${NOF}.bem << EOF

N=$N
W=$W
h=$h
L=$L
Eelectron_keV=$Eelectron_keV
E1eV=$Energy_eV
E2eV=E1eV

delta=10
NE=1
R=W/2+L

x0=0 // rectangular waveguide center at 0,0
z0=0
EeV=Eelectron_keV*1e3 // electron energy in eV

delta=400
zmax=h+delta
zmin=h*1.0001
Nz=400


photon-energy E1eV E2eV NE
grid 0 0 1 zmin zmax Nz                     // position of the electron , dont put a grid with EELS, changes the position of the electron
incident-electron-z EeV 0 h+50                     // the electron is everywhere if I put a grid 

include rectangular_wg_substrate_with_virtual_COMSOL2.bem // Silicon rectangular wg with constant epsilon to compare with Saad's COMSOL
// with bigger loss. im(epsi) = 0.2

begin-virtual-structure                          // close open structures 
add-arc 33 11 0 0  R L+W/2  0 -180 0 N4 
     

begin-calculation
calc EELS datfiles${NOFfiles}/${NOF}.dat
end-calculation                                                  

end
EOF

cat > $NOF.sh <<EOF

#!/bin/sh
#$ -cwd
#$ -j y
#$ -l h=compute-4-21

time ./bem2D bemfiles${NOFfiles}/${NOF}.bem
EOF

qsub -q NPT_new $NOF.sh

echo $(date '+%F %T') $'\t' $NOF >> qsub_EELS_spectrum.log

# rm bemfiles/$NOF.bem

mv $NOF.sh shfiles${NOFfiles}/$NOF.sh

