#!/bin/bash
#
# ./genbemax EELS rectangular waveguide varying ze (impact parameter)

Nlist=(300 400 500)
Wlist=(500)
hlist=(300)
#zelist=($(seq 10 5 100)) ## meV
Llist=(500 1000) ## nm
Hlist=(10 100) ## nm
Eelectronlist=(200)

for N in ${Nlist[@]}; do
for W in ${Wlist[@]}; do
for h in ${hlist[@]}; do
for L in ${Llist[@]}; do
for H in ${Hlist[@]}; do
for Eelectron in ${Eelectronlist[@]}; do
#  echo genbemax_electron $a $b $m $E0meV $E0meV $N
  ./genbemax_EELS_spectrum_rect_double_wg $N $W $h $L $H $Eelectron
   echo genbemax_EELS_spectrum_rect_double_wg $N $W $h $L $H $Eelectron
done
done
done
done
done
done
