#!/bin/bash
# /////////////////// defining parameters for a rectangular wg . geometry in ribbon.bem /////////////////////////////
# //     N   = the total number of parametrization points is N+50
# //     a   = total width of wg     || x (called width W now)
# //     h   = total thickness of wg  || y
# //     s   = rounding radius of wg (s<t/2)
# //     ze  = impact parameter is h/2+ze. ze distance between electron and wg surface 

N=${1:-400}
a=${2:-400}
h=${3:-300}
s=${4:-20}
EeV=${5:-0.75}
 
NOFraw='EELS_along_z_N'${N}'_a'${a}'nm_h'${h}'nm_energy'${EeV}'eV'
NOF=$(echo $NOFraw | sed -e 's/\.//g')

NOFfiles='_EELS'

#bem file
mkdir -p bemfiles${NOFfiles}
mkdir -p datfiles${NOFfiles}
mkdir -p shfiles${NOFfiles}

cat > bemfiles${NOFfiles}/${NOF}.bem << EOF

N=$N
a=$a
h=$h
s=$s
E1eV=$EeV

delta=400
NE=1
mu2=2
mu3=1
x0=0 // rectangular waveguide center at 0,0
y0=0
EeV=200e3 // electron energy in eV
zmax=h/2+delta
zmin=(h/2)*1.0001
Nz=400

epsilon mu2 Si_extra_loss.eps       // Silicon rectangular rod 

photon-energy E1eV E1eV NE
grid 0 0 1 zmin zmax Nz     // position of the electron , dont put a grid with EELS, changes the position of the electron
incident-electron-z EeV 0 h/2  // the electron is everywhere if I put a grid 
include ribbon.bem  

begin-calculation
calc EELS datfiles${NOFfiles}/${NOF}.dat
end-calculation                                                  

end
EOF

time ./bem2D bemfiles${NOFfiles}/${NOF}.bem
